"use strict";

module.exports = {
     INVALID_DATE_FORMAT_CONTAINS_INVALID_CHARACTER: "INVALID_DATE_FORMAT_CONTAINS_INVALID_CHARACTER",
     INVALID_DATE_FORMAT: "INVALID_DATE_FORMAT",
     INVALID_TWO_DIGIT_BEFORE_MIN: "INVALID_TWO_DIGIT_BEFORE_MIN",
     INVALID_TWO_DIGIT_AFTER_MAX: "INVALID_TWO_DIGIT_AFTER_MAX",
     INVALID_FOUR_DIGIT_BEFORE_MIN: "INVALID_FOUR_DIGIT_BEFORE_MIN",
     INVALID_FOUR_DIGIT_AFTER_MAX: "INVALID_FOUR_DIGIT_AFTER_MAX",
     VALID_TWO_DIGIT_YEAR: "VALID_TWO_DIGIT_YEAR",
     VALID_FOUR_DIGIT_YEAR: "VALID_FOUR_DIGIT_YEAR"
};